version: '2'
services:
  node01:
    image: aritranag20/list-product-service
    restart: always
    environment:
      - TZ=America/Montreal
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://18.210.200.8:5010"
        syslog-format: "rfc3164"
        tag: "node-01"
    ports:
      - '8200:8200'
